name: zubo

on:
  schedule:
    - cron: '0 5,19 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 获取组播源
        run: |
          cd $GITHUB_WORKSPACE
          python ./zubo.py
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yt-dlp sed nmap
        
      - name: 测试组播源
        run: |
          cd $GITHUB_WORKSPACE
          cat zubo.txt > zubo_备份.txt
          bash ./zubo2.sh
          cat txt/广东电信.txt txt/北京联通.txt txt/四川电信.txt txt/湖南电信.txt txt/广东联通.txt txt/湖北电信.txt txt/浙江电信.txt txt/江苏电信.txt txt/上海电信.txt txt/福建电信.txt txt/安徽电信.txt txt/江西电信.txt txt/天津联通.txt txt/河南电信.txt txt/河北联通.txt txt/山东电信.txt txt/陕西电信.txt txt/广西电信.txt txt/贵州电信.txt txt/山西联通.txt txt/重庆电信.txt txt/宁夏电信.txt > zubo.txt
          
      - name: 更新组播源
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "更新组播源"
          git push